sudo: required
language: node_js
node_js:
  - "7"
  - "8"
services:
  - docker
  - mysql
before_install:
  - echo '{"mysql":{"user":"travis","database":"yeps","connectionLimit":10}}' > config/default.json
  - mysql -u travis -e 'CREATE DATABASE IF NOT EXISTS yeps;'
script:
  - docker version
  - mysql --version
  - node --version
  - npm --version
  - npm run lint
  - npm run test
  - npm run report
