language: node_js
node_js:
  - "7.6"
  - "7.7"
services:
  - mysql
before_install:
  - echo '{"mysql":{"user":"travis","database":"test","connectionLimit":10}}' > config/default.json
  - mysql -u travis -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
  - npm run lint
  - npm run test
  - npm run report