environment:

  MYSQL_DATABASE: test
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: Password12!
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7

  matrix:
    - nodejs_version: "7.7"

services:
  - mysql

install:
  - ps: Install-Product node $env:nodejs_version
  - echo {"mysql":{"user":"root","password":"Password12!","database":"test","connectionLimit":10}} > config/default.json
  - npm install

before_test:
  - SET PATH=%MYSQL_PATH%\bin;%PATH%
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PASSWORD% create %MYSQL_DATABASE%

test_script:
  - mysql --version
  - node --version
  - npm --version
  - npm run lint
  - npm run test:security
  - npm run test:code

build: off