image: Visual Studio 2017
environment:
  matrix:
    - nodejs_version: "8"
install:
  - ps: Install-Product node $env:nodejs_version
  - docker pull charmingsteve/windows-mysql
  - npm install
  - docker run -d --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=yeps charmingsteve/windows-mysql
test_script:
  - docker version
  - node --version
  - npm --version
  - npm run lint
  - npm run test:security
  - npm run test:code
build: off
