environment:
  matrix:
    - nodejs_version: "7.7"
services:
  - mysql
install:
  - ps: Install-Product node $env:nodejs_version
  - echo '{"mysql":{"user":"root","password":"Password12!","database":"test","connectionLimit":10}}' > config/default.json
  - C:\Program Files\MySQL\MySQL -u root -pPassword12! -e 'CREATE DATABASE IF NOT EXISTS test;'
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test:security
  - npm run test:code
build: off