image: Visual Studio 2017
environment:
  matrix:
    - nodejs_version: "8"

install:
  - npm install
  - npm run db:start

test_script:
  - docker version
  - mysql --version
  - node --version
  - npm --version
  - npm run lint
  - npm run test:security
  - npm run test:code

build: off
